# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b85dd9524ae30f96ecd7f11f1aa82798a128399eba9fa78723d0d25eae7e360ccd22e0cdf38726175c76f455781461d6e8195eaf92dbe2ac0433d1704a1f14e0

test:
  secret_key_base: cebba2347ddec506df9e924f6458039b428f075ee2c086e9fda273a2e8f6c76a4c530aa08eca8ee1aee450b9a668cfc802ba32186395bb2cba533acc99f23bc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
